/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import static client.Medecin.openProduit;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.lang.reflect.InvocationTargetException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author loukmane04 && mati yahya
 */
public class Produit extends javax.swing.JFrame {

    /**
     * Creates new form product
     */
    public Produit() {
        setIconImage(new ImageIcon(getClass().getResource("/icons/applogo.png")).getImage());
        initComponents();
        obligatoire.setVisible(false);
        obligatoire1.setVisible(false);
        obligatoire2.setVisible(false);
        initTable();       
        loadProductData();
        jPanel5.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jTable2.setVisible(false);
        jScrollPane2.setVisible(false);
    }
     public Produit(String medecin) {
         setIconImage(new ImageIcon(getClass().getResource("/icons/applogo.png")).getImage());
        initComponents();
        initTable();
        loadProductData();
        ajouter.setVisible(false);
        np.setVisible(false);
        quantite.setVisible(false);
        dp.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);        
        jPanel4.setVisible(false);
        jPanel5.setVisible(true);
        jLabel9.setVisible(true);
        jLabel14.setVisible(false);
        jLabel10.setVisible(true);
        jLabel15.setVisible(false);
        jLabel5.setVisible(false);
        jScrollPane2.setVisible(true);
        jTable2.setVisible(true);        
        jTable1.setVisible(false);
        jScrollPane1.setVisible(false);
    }
    
     private void initTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Produit");
        model.addColumn("Quantite");
        model.addColumn("Date Peremption");
        jTable1.setModel(model);
        jTable2.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        np = new javax.swing.JTextField();
        quantite = new javax.swing.JTextField();
        dp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ajouter = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        obligatoire2 = new javax.swing.JLabel();
        obligatoire = new javax.swing.JLabel();
        obligatoire1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        comptes = new javax.swing.JButton();
        stock = new javax.swing.JButton();
        comptability = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        analyse = new javax.swing.JButton();
        MedecinStock = new javax.swing.JButton();
        dossier = new javax.swing.JButton();
        MedecinHome = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        logout1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        minimize = new javax.swing.JButton();
        colse = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QuickLab");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        np.setBackground(new java.awt.Color(213, 234, 255));
        np.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        np.setBorder(null);
        np.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npActionPerformed(evt);
            }
        });
        jPanel1.add(np, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 340, 40));
        np.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createMatteBorder(0, 0, 2, 0, Color.WHITE),
            BorderFactory.createEmptyBorder(5, 10, 5, 10)));

    quantite.setBackground(new java.awt.Color(213, 234, 255));
    quantite.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    quantite.setBorder(null);
    quantite.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            quantiteActionPerformed(evt);
        }
    });
    jPanel1.add(quantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 340, 40));
    quantite.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createMatteBorder(0, 0, 2, 0, Color.WHITE),
        BorderFactory.createEmptyBorder(5, 10, 5, 10)));

dp.setBackground(new java.awt.Color(213, 234, 255));
dp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
dp.setBorder(null);
jPanel1.add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 340, 40));
dp.setBorder(BorderFactory.createCompoundBorder(
    BorderFactory.createMatteBorder(0, 0, 2, 0, Color.WHITE),
    BorderFactory.createEmptyBorder(5, 10, 5, 10)));

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel5.setText("Date De Peremption");
    jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, -1, -1));

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel3.setText("Quantite");
    jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, -1));

    jLabel1.setBackground(new java.awt.Color(255, 255, 255));
    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel1.setText("Nom De Produit");
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

    jScrollPane1.setBackground(new java.awt.Color(0, 115, 194));
    jScrollPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

    jTable1.setAutoCreateRowSorter(true);
    jTable1.setBackground(new java.awt.Color(213, 234, 255));
    jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {},
            {},
            {},
            {}
        },
        new String [] {

        }
    ));
    jTable1.setToolTipText("");
    jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jTable1.setFillsViewportHeight(true);
    jTable1.setFocusCycleRoot(true);
    jTable1.setFocusTraversalPolicy(null);
    jTable1.setFocusTraversalPolicyProvider(true);
    jTable1.setGridColor(new java.awt.Color(213, 234, 255));
    jTable1.setName(""); // NOI18N
    jTable1.setSelectionBackground(new java.awt.Color(0, 115, 194));
    jTable1.setShowGrid(true);
    jTable1.setSurrendersFocusOnKeystroke(true);
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            jTable1MouseReleased(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);
    jTable1.setFont(new Font("Segoe UI", Font.BOLD, 14)); // Font for body
    jTable1.setBackground(new Color(213, 234, 255)); // Background color for body
    jTable1.setRowHeight(25);
    jTable1.setSelectionBackground(new Color(0, 115, 194)); // Selection background color
    jTable1.setSelectionForeground(Color.BLACK); // Selection text color

    // Header styling
    JTableHeader header = jTable1.getTableHeader();
    header.setBackground(new Color(0, 115, 194)); // Background color for header
    header.setForeground(Color.BLACK); // Text color for header
    header.setFont(new Font("Segoe UI", Font.BOLD, 16)); // Font for header

    // Centering header text
    ((DefaultTableCellRenderer)header.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);

    // Custom cell rendering for body
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(JLabel.CENTER);
    centerRenderer.setBackground(new Color(213, 234, 255));
    jTable1.setDefaultRenderer(Object.class, centerRenderer);

    jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 870, 420));

    ajouter.setBackground(new java.awt.Color(0, 115, 194));
    ajouter.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    ajouter.setForeground(new java.awt.Color(255, 255, 255));
    ajouter.setText("AJOUTER");
    ajouter.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ajouterActionPerformed(evt);
        }
    });
    jPanel1.add(ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 680, 340, 70));
    ajouter.setFocusPainted(false);
    ajouter.setBorderPainted(false);
    ajouter.setContentAreaFilled(false);
    ajouter.setOpaque(true);
    ajouter.setBackground(new Color(0, 115, 194)); // Set default background to white

    ajouter.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            ajouter.setBackground(new Color(23,142,224)); // Change to light gray on hover
        }

        @Override
        public void mouseExited(MouseEvent e) {
            ajouter.setBackground(new Color(0, 115, 194)); // Revert to white when not hovered
        }
    });

    jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
    jLabel9.setText("Les Informations Des Produits Disponibles Sur Le Stock");
    jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

    jLabel10.setBackground(new java.awt.Color(255, 255, 255));
    jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-view-details-55.png"))); // NOI18N
    jLabel10.setLabelFor(jLabel1);
    jLabel10.setText("Verifier L'etat De Stock");
    jLabel10.setIconTextGap(20);
    jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 570, 60));

    jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
    jLabel14.setText("Les Informations De Produit");
    jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

    jLabel15.setBackground(new java.awt.Color(255, 255, 255));
    jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-add-55.png"))); // NOI18N
    jLabel15.setLabelFor(jLabel1);
    jLabel15.setText("Ajouter Un Produit Au Stock ");
    jLabel15.setIconTextGap(20);
    jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 570, 60));

    jScrollPane2.setBackground(new java.awt.Color(0, 115, 194));
    jScrollPane2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

    jTable2.setAutoCreateRowSorter(true);
    jTable2.setBackground(new java.awt.Color(213, 234, 255));
    jTable2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jTable2.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {},
            {},
            {},
            {}
        },
        new String [] {

        }
    ));
    jTable2.setToolTipText("");
    jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jTable2.setFillsViewportHeight(true);
    jTable2.setFocusCycleRoot(true);
    jTable2.setFocusTraversalPolicyProvider(true);
    jTable2.setGridColor(new java.awt.Color(213, 234, 255));
    jTable2.setName(""); // NOI18N
    jTable2.setSelectionBackground(new java.awt.Color(0, 115, 194));
    jTable2.setShowGrid(true);
    jTable2.setSurrendersFocusOnKeystroke(true);
    jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            jTable2MouseReleased(evt);
        }
    });
    jScrollPane2.setViewportView(jTable2);
    jTable2.setFont(new Font("Segoe UI", Font.BOLD, 14)); // Font for body
    jTable2.setBackground(new Color(213, 234, 255)); // Background color for body
    jTable2.setRowHeight(25);
    jTable2.setSelectionBackground(new Color(0, 115, 194)); // Selection background color
    jTable2.setSelectionForeground(Color.BLACK); // Selection text color

    // Header styling
    JTableHeader header1 = jTable2.getTableHeader();
    header1.setBackground(new Color(0, 115, 194)); // Background color for header
    header1.setForeground(Color.BLACK); // Text color for header
    header1.setFont(new Font("Segoe UI", Font.BOLD, 16)); // Font for header

    // Centering header text
    ((DefaultTableCellRenderer)header1.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);

    // Custom cell rendering for body
    DefaultTableCellRenderer centerRenderer1 = new DefaultTableCellRenderer();
    centerRenderer1.setHorizontalAlignment(JLabel.CENTER);
    centerRenderer1.setBackground(new Color(213, 234, 255));
    jTable2.setDefaultRenderer(Object.class, centerRenderer1);

    jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 1400, 550));

    obligatoire2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    obligatoire2.setForeground(new java.awt.Color(204, 0, 0));
    obligatoire2.setText("*");
    jPanel1.add(obligatoire2, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 565, -1, 20));

    obligatoire.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    obligatoire.setForeground(new java.awt.Color(204, 0, 0));
    obligatoire.setText("*");
    jPanel1.add(obligatoire, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 10, -1));

    obligatoire1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    obligatoire1.setForeground(new java.awt.Color(204, 0, 0));
    obligatoire1.setText("*");
    jPanel1.add(obligatoire1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 10, -1));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));
    jPanel1.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            jPanel1.requestFocusInWindow();  // Request focus when panel is clicked
        }
    });
    jPanel1.setFocusable(true);  // Make the panel focusable

    jPanel4.setBackground(new java.awt.Color(0, 98, 166));
    jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    comptes.setBackground(new java.awt.Color(0, 105, 170));
    comptes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    comptes.setForeground(new java.awt.Color(255, 255, 255));
    comptes.setText("Gérer Les Employés");
    comptes.setToolTipText("");
    comptes.setBorder(null);
    comptes.setBorderPainted(false);
    comptes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    comptes.setDoubleBuffered(true);
    comptes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    comptes.setIconTextGap(50);
    comptes.setName(""); // NOI18N
    comptes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    comptes.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            comptesActionPerformed(evt);
        }
    });
    jPanel4.add(comptes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 320, 70));
    comptes.setFocusPainted(false);
    comptes.setBorderPainted(false);
    comptes.setContentAreaFilled(false);
    comptes.setOpaque(true);

    comptes.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            comptes.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
        }

        @Override
        public void mouseExited(MouseEvent e) {
            comptes.setBackground(new Color(0,105,170)); // Original color when mouse not hovering
        }
    });

    stock.setBackground(new java.awt.Color(0, 120, 200));
    stock.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    stock.setForeground(new java.awt.Color(255, 255, 255));
    stock.setText("Gérer le Stock");
    stock.setBorder(null);
    stock.setBorderPainted(false);
    stock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    stock.setDoubleBuffered(true);
    stock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    stock.setIconTextGap(50);
    stock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    stock.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            stockActionPerformed(evt);
        }
    });
    jPanel4.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 320, 70));
    stock.setFocusPainted(false);
    stock.setBorderPainted(false);
    stock.setContentAreaFilled(false);
    stock.setOpaque(true);

    stock.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            stock.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
        }

        @Override
        public void mouseExited(MouseEvent e) {
            stock.setBackground(new Color(0,120,200)); // Original color when mouse not hovering
        }
    });

    comptability.setBackground(new java.awt.Color(0, 105, 170));
    comptability.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    comptability.setForeground(new java.awt.Color(255, 255, 255));
    comptability.setText("Consulter Les Revunus");
    comptability.setBorder(null);
    comptability.setBorderPainted(false);
    comptability.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    comptability.setDoubleBuffered(true);
    comptability.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    comptability.setIconTextGap(50);
    comptability.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    comptability.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            comptabilityActionPerformed(evt);
        }
    });
    jPanel4.add(comptability, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 320, 70));
    comptability.setFocusPainted(false);
    comptability.setBorderPainted(false);
    comptability.setContentAreaFilled(false);
    comptability.setOpaque(true);

    comptability.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            comptability.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
        }

        @Override
        public void mouseExited(MouseEvent e) {
            comptability.setBackground(new Color(0,105,170)); // Original color when mouse not hovering
        }
    });

    home.setBackground(new java.awt.Color(0, 105, 170));
    home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    home.setForeground(new java.awt.Color(255, 255, 255));
    home.setText("Accueil");
    home.setToolTipText("");
    home.setBorder(null);
    home.setBorderPainted(false);
    home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    home.setDoubleBuffered(true);
    home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    home.setIconTextGap(50);
    home.setName(""); // NOI18N
    home.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    home.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            homeActionPerformed(evt);
        }
    });
    jPanel4.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 320, 70));
    home.setFocusPainted(false);
    home.setBorderPainted(false);
    home.setContentAreaFilled(false);
    home.setOpaque(true);

    home.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            home.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
        }

        @Override
        public void mouseExited(MouseEvent e) {
            home.setBackground(new Color(0,105,170)); // Original color when mouse not hovering
        }
    });

    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel7.setText("Gérant");
    jLabel7.setMaximumSize(new java.awt.Dimension(100, 16));
    jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 320, -1));

    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-user-100.png"))); // NOI18N
    jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, 150, 150));

    logout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    logout.setForeground(new java.awt.Color(0, 115, 194));
    logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-log-out-30.png"))); // NOI18N
    logout.setText("Déconnexion");
    logout.setBorder(null);
    logout.setBorderPainted(false);
    logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    logout.setDoubleBuffered(true);
    logout.setIconTextGap(5);
    logout.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            logoutActionPerformed(evt);
        }
    });
    jPanel4.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 901, 220, 60));
    logout.setFocusPainted(false);
    logout.setBorderPainted(false);
    logout.setContentAreaFilled(false);
    logout.setOpaque(true);
    logout.setBackground(new Color(255, 255, 255)); // Set default background to white

    logout.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            logout.setBackground(new Color(240,240,240)); // Change to light gray on hover
        }

        @Override
        public void mouseExited(MouseEvent e) {
            logout.setBackground(new Color(255, 255, 255)); // Revert to white when not hovered
        }
    });

    getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 1000));

    jPanel5.setBackground(new java.awt.Color(0, 98, 166));
    jPanel5.setPreferredSize(new java.awt.Dimension(320, 1000));
    jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    analyse.setBackground(new java.awt.Color(0, 105, 170));
    analyse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    analyse.setForeground(new java.awt.Color(255, 255, 255));
    analyse.setText("Gestion d'analyse");
    analyse.setToolTipText("");
    analyse.setBorder(null);
    analyse.setBorderPainted(false);
    analyse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    analyse.setDoubleBuffered(true);
    analyse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    analyse.setIconTextGap(50);
    analyse.setName(""); // NOI18N
    analyse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    analyse.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            analyseActionPerformed(evt);
        }
    });
    jPanel5.add(analyse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 320, 70));
    analyse.setFocusPainted(false);
    analyse.setBorderPainted(false);
    analyse.setContentAreaFilled(false);
    analyse.setOpaque(true);

    analyse.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            analyse.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
        }

        @Override
        public void mouseExited(MouseEvent e) {
            analyse.setBackground(new Color(0, 105, 170)); // Original color when mouse not hovering
        }
    });

    MedecinStock.setBackground(new java.awt.Color(0, 120, 200));
    MedecinStock.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    MedecinStock.setForeground(new java.awt.Color(255, 255, 255));
    MedecinStock.setText("Verifier l'état de Stock");
    MedecinStock.setBorder(null);
    MedecinStock.setBorderPainted(false);
    MedecinStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    MedecinStock.setDoubleBuffered(true);
    MedecinStock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    MedecinStock.setIconTextGap(50);
    MedecinStock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    MedecinStock.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            MedecinStockActionPerformed(evt);
        }
    });
    jPanel5.add(MedecinStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 320, 70));
    MedecinStock.setFocusPainted(false);
    MedecinStock.setBorderPainted(false);
    MedecinStock.setContentAreaFilled(false);
    MedecinStock.setOpaque(true);

    MedecinStock.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            MedecinStock.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
        }

        @Override
        public void mouseExited(MouseEvent e) {
            MedecinStock.setBackground(new Color(0, 120, 200)); // Original color when mouse not hovering
        }
    });

    dossier.setBackground(new java.awt.Color(0, 105, 170));
    dossier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    dossier.setForeground(new java.awt.Color(255, 255, 255));
    dossier.setText("Consulter Dossier Patient");
    dossier.setBorder(null);
    dossier.setBorderPainted(false);
    dossier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    dossier.setDoubleBuffered(true);
    dossier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    dossier.setIconTextGap(50);
    dossier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    dossier.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            dossierActionPerformed(evt);
        }
    });
    jPanel5.add(dossier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 320, 70));
    dossier.setFocusPainted(false);
    dossier.setBorderPainted(false);
    dossier.setContentAreaFilled(false);
    dossier.setOpaque(true);

    dossier.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            dossier.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
        }

        @Override
        public void mouseExited(MouseEvent e) {
            dossier.setBackground(new Color(0, 105, 170)); // Original color when mouse not hovering
        }
    });

    MedecinHome.setBackground(new java.awt.Color(0, 105, 170));
    MedecinHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    MedecinHome.setForeground(new java.awt.Color(255, 255, 255));
    MedecinHome.setText("Accueil");
    MedecinHome.setToolTipText("");
    MedecinHome.setBorder(null);
    MedecinHome.setBorderPainted(false);
    MedecinHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    MedecinHome.setDoubleBuffered(true);
    MedecinHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    MedecinHome.setIconTextGap(50);
    MedecinHome.setName(""); // NOI18N
    MedecinHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    MedecinHome.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            MedecinHomeActionPerformed(evt);
        }
    });
    jPanel5.add(MedecinHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 320, 70));
    MedecinHome.setFocusPainted(false);
    MedecinHome.setBorderPainted(false);
    MedecinHome.setContentAreaFilled(false);
    MedecinHome.setOpaque(true);

    MedecinHome.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            MedecinHome.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
        }

        @Override
        public void mouseExited(MouseEvent e) {
            MedecinHome.setBackground(new Color(0, 105, 170)); // Original color when mouse not hovering
        }
    });

    jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel12.setForeground(new java.awt.Color(255, 255, 255));
    jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel12.setText("Médecin");
    jLabel12.setMaximumSize(new java.awt.Dimension(100, 16));
    jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 320, -1));

    jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-user-100.png"))); // NOI18N
    jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, 150, 150));

    logout1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    logout1.setForeground(new java.awt.Color(0, 115, 194));
    logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-log-out-30.png"))); // NOI18N
    logout1.setText("Déconnexion");
    logout1.setBorder(null);
    logout1.setBorderPainted(false);
    logout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    logout1.setDoubleBuffered(true);
    logout1.setIconTextGap(5);
    logout1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            logout1ActionPerformed(evt);
        }
    });
    jPanel5.add(logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 901, 220, 60));
    logout1.setFocusPainted(false);
    logout1.setBorderPainted(false);
    logout1.setContentAreaFilled(false);
    logout1.setOpaque(true);
    logout1.setBackground(new Color(255, 255, 255)); // Set default background to white

    logout1.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            logout1.setBackground(new Color(240,240,240)); // Change to light gray on hover
        }

        @Override
        public void mouseExited(MouseEvent e) {
            logout1.setBackground(new Color(255, 255, 255)); // Revert to white when not hovered
        }
    });

    getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 320, 1000));

    jPanel2.setBackground(new java.awt.Color(0, 0, 0));
    jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    minimize.setBackground(new java.awt.Color(0, 0, 0));
    minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-minimize-30.png"))); // NOI18N
    minimize.setBorder(null);
    minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    minimize.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            minimizeActionPerformed(evt);
        }
    });
    jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1820, 0, 40, 40));
    minimize.setFocusPainted(false);
    minimize.setBorderPainted(false);
    minimize.setContentAreaFilled(false);
    minimize.setOpaque(true);

    minimize.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            minimize.setBackground(new Color(20,20,20)); // Darker blue when mouse hovers
        }

        @Override
        public void mouseExited(MouseEvent e) {
            minimize.setBackground(new Color(0, 0,0)); // Original color when mouse not hovering
        }
    });

    colse.setBackground(new java.awt.Color(0, 0, 0));
    colse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-close-30.png"))); // NOI18N
    colse.setBorder(null);
    colse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    colse.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            colseActionPerformed(evt);
        }
    });
    jPanel2.add(colse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1870, 0, 40, 40));
    colse.setFocusPainted(false);
    colse.setBorderPainted(false);
    colse.setContentAreaFilled(false);
    colse.setOpaque(true);

    colse.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            colse.setBackground(new Color(20,20,20)); // Darker blue when mouse hovers
        }

        @Override
        public void mouseExited(MouseEvent e) {
            colse.setBackground(new Color(0, 0,0)); // Original color when mouse not hovering
        }
    });

    jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel16.setForeground(new java.awt.Color(255, 255, 255));
    jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel16.setText("QuickLab");
    jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 320, 40));

    getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 40));

    setSize(new java.awt.Dimension(1920, 1040));
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
         String npValue = np.getText();
        String quantiteValue = quantite.getText();
        String dpValue = dp.getText();
        
         if (npValue.trim().isEmpty()) {
        
        obligatoire.setVisible(true);
         // Stop further execution if nom is empty
    }else{
         obligatoire.setVisible(false);
        
    }
    if (quantiteValue.trim().isEmpty()) {
        
        obligatoire1.setVisible(true);
         // Stop further execution if nom is empty
    }else{
         obligatoire1.setVisible(false);
        
    }
    if (dpValue.trim().isEmpty()) {
        
        obligatoire2.setVisible(true);
         // Stop further execution if nom is empty
    }else{
         obligatoire2.setVisible(false);
        
    }
         
     if(!npValue.trim().isEmpty() && !quantiteValue.trim().isEmpty() && !dpValue.trim().isEmpty()){
         
           Client.sendProduitInfo(npValue, quantiteValue, dpValue);
           
        JOptionPane.showMessageDialog(null, "Produit ajouté avec succès", "Succès", JOptionPane.INFORMATION_MESSAGE);
        
       
        
       // Update the user in the table model by adding a new row
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{npValue, quantiteValue, dpValue});
    
      // clear text field
        np.setText("");
        quantite.setText("");
        dp.setText("");
     }
        // Send the data to the Client class
      
    }//GEN-LAST:event_ajouterActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseReleased

    private void comptesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comptesActionPerformed
        smoothTransition("client.Ajouter_Compte", 1000);
    }//GEN-LAST:event_comptesActionPerformed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        smoothTransition("client.Produit", 1000);
    }//GEN-LAST:event_stockActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed

        java.awt.EventQueue.invokeLater(() -> {
            //new Gerant().setVisible(true);
            //setVisible(false);
            smoothTransition("client.Gerant", 1000);
        });

    }//GEN-LAST:event_homeActionPerformed

    private void quantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantiteActionPerformed

    private void npActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npActionPerformed

    private void analyseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyseActionPerformed
        smoothTransition("client.Gérer_Analyse_Medicale", 1000);
    }//GEN-LAST:event_analyseActionPerformed

    private void MedecinStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedecinStockActionPerformed
        smoothTransition("client.Produit", 1000, "medecin");

    }//GEN-LAST:event_MedecinStockActionPerformed

    private void dossierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dossierActionPerformed
       smoothTransition("client.Dossier", 1000, "medecin");
    }//GEN-LAST:event_dossierActionPerformed

    private void MedecinHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedecinHomeActionPerformed
      smoothTransition("client.Medecin", 1000);
    }//GEN-LAST:event_MedecinHomeActionPerformed

    private void jTable2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseReleased

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        setExtendedState(getExtendedState() | Gérer_Analyse_Medicale.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void colseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colseActionPerformed

        System.exit(0);
    }//GEN-LAST:event_colseActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logout1ActionPerformed

    private void comptabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comptabilityActionPerformed
     smoothTransition("client.Overview", 1000);   
    }//GEN-LAST:event_comptabilityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produit().setVisible(true);
            }
        });
    }
            

private void loadProductData() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    String productData = Client.fetchProductData(); // Fetch product data from the server
    if (productData == null) {
        System.out.println("Failed to receive data from the server.");
        return; // Handle no data or connection error.
    }

    if (productData.equals("No product found")) {
        System.out.println("No products found on the server.");
        return; // Handle no products found.
    }

    // Assuming each product's data is separated by a semicolon
    String[] productEntries = productData.split(";");
    for (String entry : productEntries) {
        String[] dataParts = entry.split(":");
        // Ensure there are exactly three parts corresponding to the three columns
        if (dataParts.length == 3) {
            SwingUtilities.invokeLater(() -> {
                model.addRow(dataParts); // Update model on the EDT
            });
        } else {
            System.out.println("Received product data in an unexpected format: " + entry);
        }
    }
}



//By: OussamaDeV


private void smoothTransition(String windowName, int delayMilliseconds) {
    // Initialize the Timer outside the EventQueue.invokeLater call
    Timer timer = new Timer(delayMilliseconds, null);

    java.awt.EventQueue.invokeLater(() -> {
        try {
            // Dynamically create an instance of the specified window class
            Class<?> clazz = Class.forName(windowName);
            java.awt.Window window = (java.awt.Window) clazz.getDeclaredConstructor().newInstance();
            
            // Make the window visible
            window.setVisible(true);

            // Update the Timer's ActionListener here
            timer.addActionListener((e) -> {
                // Hide the current window after the delay
                setVisible(false);
                
                // Stop the Timer
                timer.stop();
            });

            // Start the Timer
            timer.start();
        } catch (ClassNotFoundException | NoSuchMethodException | InstantiationException | IllegalAccessException | InvocationTargetException ex) {
            // Handle any exceptions
            ex.printStackTrace();
        }
    });
}
    
    
private void smoothTransition(String windowName, int delayMilliseconds, Object... constructorArgs) {
    // Initialize the Timer outside the EventQueue.invokeLater call
    Timer timer = new Timer(delayMilliseconds, null);

    java.awt.EventQueue.invokeLater(() -> {
        try {
            // Dynamically create an instance of the specified window class
            Class<?> clazz = Class.forName(windowName);
            // Determine parameter types from constructorArgs
            Class<?>[] parameterTypes = new Class<?>[constructorArgs.length];
            for (int i = 0; i < constructorArgs.length; i++) {
                parameterTypes[i] = constructorArgs[i].getClass();
            }
            java.awt.Window window = (java.awt.Window) clazz.getDeclaredConstructor(parameterTypes).newInstance(constructorArgs);
            
            // Make the window visible
            window.setVisible(true);

            // Update the Timer's ActionListener here
            timer.addActionListener((e) -> {
                // Hide the current window after the delay
                setVisible(false);
                
                // Stop the Timer
                timer.stop();
            });

            // Start the Timer
            timer.start();
        } catch (ClassNotFoundException | NoSuchMethodException | InstantiationException | IllegalAccessException | InvocationTargetException ex) {
            // Handle any exceptions
            ex.printStackTrace();
        }
    });
}    
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MedecinHome;
    private javax.swing.JButton MedecinStock;
    private javax.swing.JButton ajouter;
    private javax.swing.JButton analyse;
    private javax.swing.JButton colse;
    private javax.swing.JButton comptability;
    private javax.swing.JButton comptes;
    private javax.swing.JButton dossier;
    private javax.swing.JTextField dp;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton logout;
    private javax.swing.JButton logout1;
    private javax.swing.JButton minimize;
    private javax.swing.JTextField np;
    private javax.swing.JLabel obligatoire;
    private javax.swing.JLabel obligatoire1;
    private javax.swing.JLabel obligatoire2;
    private javax.swing.JTextField quantite;
    private javax.swing.JButton stock;
    // End of variables declaration//GEN-END:variables
}
